miho/__init__.py
from functools import partial

from flask import Flask
from werkzeug.routing import BaseConverter

from . import utils


def create_app(config_file) -> Flask:
    app = Flask(__name__, static_url_path='/images', static_folder='../images')
    app.config.from_pyfile(str(config_file))
    app.url_map.converters['color'] = ColorConverter
    register_blueprints(app)
    return app


def register_blueprints(app: Flask):
    from .views.api import api
    from .views.web import web

    api.before_request(partial(utils.restrict_with_base_auth, 'API'))
    web.before_request(partial(utils.restrict_with_base_auth, 'WEB'))

    app.register_blueprint(web)
    app.register_blueprint(api, url_prefix='/api')


class ColorConverter(BaseConverter):
    regex = r'([a-fA-F0-9]{3}|[a-fA-F0-9]{6})'

miho/views/api.py
from contextlib import closing
from functools import partial
import hashlib
import pathlib


from flask import Blueprint, jsonify, request, url_for
from PIL import Image

from .. import utils

api = Blueprint('api', __name__)


@api.route('/')
def index():
    return jsonify()


@api.route('/upload', methods=['POST'])
def upload():
    if 'image' not in request.files:
        return jsonify(error='nothing to upload'), 400

    images_dir = utils.get_images_dir()
    while True:
        tmp_file = '.' + utils.randstr(100)
        tmp_path = pathlib.Path(images_dir, tmp_file)
        if not tmp_path.exists():
            break

    image = request.files['image']
    digest = hashlib.sha256()
    with closing(image.stream) as fin, tmp_path.open('wb') as fout:
        for chunk in iter(partial(fin.read, 64 << 10), b''):
            digest.update(chunk)
            fout.write(chunk)

    file_hash = digest.hexdigest()

    try:
        img = Image.open(tmp_path)
    except OSError:
        tmp_path.unlink()
        return jsonify(error='Invalid or unknown image format'), 400

    extension = {
        'jpeg': 'jpg',
        'jpg': 'jpg',
        'png': 'png',
        'gif': 'gif',
    }.get(img.format.lower(), None)

    if extension is None:
        tmp_path.unlink()
        return jsonify(error='unsupported format'), 400

    width, height = img.size
    sub_hash = file_hash[0:17]
    filename = '{}-{}-{}.{}'.format(sub_hash, width, height, extension)

    index = 0
    for im in utils.get_images():
        if im.filename == filename:
            tmp_path.unlink()
            img.close()
            return jsonify(error='file already exists', fn=im.fullname), 400
        index = max(index, im.index)

    index += 1

    new_filename = '{:06d}-{}'.format(index, filename)
    new_path = pathlib.Path(tmp_path.parent, new_filename)
    tmp_path.rename(new_path)

    thumb1_path = pathlib.Path(new_path.parent, 'thumbs', '{:06d}-1-{}.jpg'.format(index, filename))
    thumb2_path = pathlib.Path(new_path.parent, 'thumbs', '{:06d}-2-{}.jpg'.format(index, filename))

    t1 = img.convert('RGB')
    t1.thumbnail((512, 512), Image.BICUBIC)
    t1.save(str(thumb1_path), quality=85)
    t1.close()

    t2 = img.convert('RGB')
    t2.thumbnail((200, 200), Image.BICUBIC)
    t2.save(str(thumb2_path), quality=85)
    t2.close()

    return jsonify(success=url_for('static', filename=new_filename, _external=True))


@api.route('/delete/<id_or_fullname>', methods=['DELETE'])
def delete(id_or_fullname):
    images_dir = utils.get_images_dir()
    if id_or_fullname.isdigit():
        img = utils.find_by_id(int(id_or_fullname))
    else:
        m = utils.match_image(id_or_fullname)
        if m is None:
            return jsonify(error='invalid id or filename'), 400
        img = utils.match_to_tuple(m)

    if img is None:
        return jsonify(error='file does not exist'), 404

    image_path = pathlib.Path(images_dir, img.fullname)
    preview_path = pathlib.Path(images_dir, 'thumbs', img.preview)
    thumbnail_path = pathlib.Path(images_dir, 'thumbs', img.thumbnail)

    deleted_something = False
    if image_path.exists():
        deleted_something = True
        image_path.unlink()

    if preview_path.exists():
        deleted_something = True
        preview_path.unlink()

    if thumbnail_path.exists():
        deleted_something = True
        thumbnail_path.unlink()

    if deleted_something:
        return jsonify(success='file deleted')
    return jsonify(error='file does not exist'), 404

miho/views/web.py
from flask import Blueprint, render_template, Response

from .. import utils

web = Blueprint('web', __name__)


@web.route('/')
def index():
    images = list(utils.get_images())
    images.sort(reverse=True)
    return render_template('index.html', images=images)


@web.route('/spinner.svg')
@web.route('/<color:color>/spinner.svg')
def spinner(color='000'):
    return Response(render_template('spinner.svg', color=color), mimetype='image/svg+xml')

miho/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Miho</title>
    <link rel="icon" type="image/png"
          href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAA7AAAAOwBeShxvQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAEGSURBVFiF7ZYxDoIwFIY/GAxXcPQwnolRRjyADg5iwjH0KuKE8QhsOlAVSoWXUmCQP/kTaKHve23TPpg1CxbAFrgDz5GcA7GKTTxiYN2xpzJf9p1GSz08RaIrAy7qeQ2shqTQp+UIBJX+AEgM37ly7eWqBa9CZEMA+FqgM1AYAAq+S+JUOoDnaNy9skiulyCq/BcJvm80JDQ34ckiuBTC2JgBB+Vbj+ASCCe7edMS/K3QFmCnbJO5ZCbEmZkykGSuSwxgGjzs6HcGELUMEHX09wawzcwKwHQbujoN2wA+0o/i0TU5wK+CZDT5lCXZVMp9IJ0QIIWyNI4pS2UX94LEtbJ81n/rBZZGPZ+FgrfRAAAAAElFTkSuQmCC">
    <style>
        * {
            box-sizing: border-box;
            font-family: sans-serif;
            font-size: 18px;
        }

        html, body {
            padding: 0;
            margin: 0;
        }

        .main {
            width: 1200px;
            max-width: 100%;
            margin: 0 auto;
            padding: 15px;
        }

        .image-list {
            margin: 0 -15px;
        }

        .image-list:after, .image-list:before {
            content: "";
            display: block;
            clear: both;
        }

        .image-wrap {
            float: left;
            padding: 0 15px;
            margin-bottom: 30px;
            width: 20%;
        }

        .image {
            width: 100%;
            padding-top: 100%;
            height: 0;
            position: relative;
        }

        .image-shift {
            position: absolute;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
        }

        .image a {
            display: block;
            height: 100%;
            width: 100%;
            padding: 10px;
            border: 1px solid #d0d0d0;
            border-radius: 10px;
            background-color: #f9f9f9;
        }

        .image img {
            display: block;
            max-width: 100%;
            max-height: 100%;
            width: auto;
            height: auto;
            position: relative;
            top: 50%;
            transform: translateY(-50%);
            margin: 0 auto;
            z-index: 5;
        }
        .image-overlay {
            position: absolute;
            z-index: 10;
            font-size: 0.8em;
            color: black;
            display: block;
            background: rgba(255,255,255,0.6);
            padding: 2px;
        }
        .image-index {
            top: 8px;
            left: 8px;
        }
        .image-data {
            bottom: 8px;
            right: 8px;
        }

        @media (max-width: 1200px) {  .image-wrap {width: 25%;}  }
        @media (max-width: 900px) {  .image-wrap {width: 33.3333333%;}  }
        @media (max-width: 650px) {  .image-wrap {width: 50%;}  }
        @media (max-width: 650px) {  .image-wrap {width: 50%;}  }
        @media (max-width: 450px) {  .image-wrap {width: 100%; float: none;}  }
    </style>
    <script>
        function getAbsoluteTop(elem) {
            let top = 0;
            let current = elem;
            while(current !== null) {
                top += current.offsetTop;
                current = current.offsetParent;
            }
            return top;
        }

        function between(t, a, b) {
            if (b < a) {
                return t >= b && t <= a;
            }
            return t >= a && t <= b;
        }

        function update_visible_images(){
            let htmlCollection = document.getElementsByTagName('img');
            let images = Array.prototype.slice.call(htmlCollection);

            let windowTop = window.scrollY;
            let windowHeight = window.innerHeight || document.body.clientHeight || document.documentElement.clientHeight;
            let windowBottom = windowTop + windowHeight;

            let padding = 0;

            images.forEach(function(img){
                if (!img.hasAttribute('data-src')) {
                    return;
                }
                let dataSrc = img.getAttribute('data-src');
                if (dataSrc === '' || !dataSrc) {
                    return;
                }
                let box = img.parentElement;  // a-tag
                let boxTop = getAbsoluteTop(box);
                let boxHeight = box.offsetHeight;
                let boxBottom = boxTop + boxHeight;

                // partially visible
                if (
                    between(boxTop + padding, windowTop, windowBottom)
                    || between(boxBottom - padding, windowTop, windowBottom)
                ) {
                    img.setAttribute('src', dataSrc);
                    img.setAttribute('data-src', '');
                }
            });
        }

        window.addEventListener('scroll', update_visible_images);
        window.addEventListener('resize', update_visible_images);
        window.addEventListener('load', update_visible_images);
    </script>
</head>
<body>

<div class="main">
    <div class="image-list">
    {% for image in images %}
        <div class="image-wrap">
            <div class="image">
                <div class="image-shift">
                    <a href="{{ url_for('static', filename=image.fullname) }}" target="_blank">
                        <img src="{{ url_for('web.spinner') }}" data-src="{{ url_for('static', filename='thumbs/' + image.preview) }}">
                        <span class="image-index image-overlay">#{{ image.index }}</span>
                        <span class="image-data image-overlay">{{ image.width }}x{{ image.height }} ({{ image.ext }})</span>
                    </a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>

</body>
</html>